### ISSUE TITLE
[err] 无法从 blog 创建评注

### ISSUE THREAD

**Issue by ZoomQuiet** [tisonkun/blog#70]
![72671678031063_ pic](https://user-images.githubusercontent.com/22494/222970907-29989990-bc38-4250-8729-086ac7831527.jpg)

- 提交了两次, 显示是 login 的
- 但是, 并没能创建对应评注
-  推荐 utterances https://utteranc.es/ 来的稳定....简单够用了

**Comment by tisonkun** [comment]
https://github.com/tisonkun/blog/discussions/66 我看是可以创建，但是显示有问题。

**Comment by tisonkun** [comment]
Should be fixed by cd8621e26554283d09f00b62893bf6c6a91de7a9

**Comment by tisonkun** [comment]
Verified fixed.
